name: SystemPlugin
main: System\Main
version: 1.2.0-2
api: [1.11.0]
load: POSTWORLD
website:
author: hiroki19990625
commands:
 login:
  description:
  usage: "/login <password>"
 register:
  description:
  usage: "/register <password>"
 magic:
  description:
  usage: "/magic <help/info/set>"
 ma:
  description:
  usage: "/ma <help/info/set>"
 t:
  description:
  usage: "/t <add/del>"
 init:
  description:
  usage: "/init"
 invc:
  description:
  usage: "/invc"
